// Copyright © 2026 wyksoftsinc.com. All rights reserved.
// Created by Wycliff Njenga on 30/09/2026.

import 'package:flutter/widgets.dart';

/// Every string the chat kit shows or announces, in English, Swahili and French. Set [provider]
/// to override them or add languages.
abstract final class KitoChatStrings {
  /// Consulted first; return null to fall back to the bundled strings.
  static String? Function(String key, Locale locale)? provider;

  /// The bundled strings, by language code. Placeholders are written `{name}`.
  static const Map<String, Map<String, String>> bundled = {
    'en': {
      'message': 'Message',
      'photo': 'Photo',
      'photoCaption': 'Photo: {caption}',
      'voiceMessage': 'Voice message',
      'voiceMessageLength': 'Voice message ({duration})',
      'voicePreview': '🎤 Voice message · {duration}',
      'photoPreview': '📷 {caption}',
      'you': 'You',
      'youPrefix': 'You: {text}',
      'today': 'Today',
      'yesterday': 'Yesterday',
      'typing': 'Typing',
      'typingInline': 'typing',
      'typing1': '{a} is typing…',
      'typing2': '{a} and {b} are typing…',
      'typing3': '{a}, {b} and {c} are typing…',
      'typingMany': '{a}, {b} and {n} others are typing…',
      'online': 'Online',
      'nameOnline': '{name}, online',
      'unread1': '1 unread message',
      'unreadMany': '{n} unread messages',
      'unreadCount': '{n} unread',
      'sending': 'Sending',
      'sent': 'Sent',
      'delivered': 'Delivered',
      'read': 'Read',
      'failed': 'Not delivered',
      'retry': 'Not delivered · Tap to retry',
      'retryLabel': 'Not delivered. Retry',
      'reply': 'Reply',
      'copy': 'Copy',
      'delete': 'Delete',
      'close': 'Close',
      'reactWith': 'React with {emoji}',
      'reactHeart': 'React with a heart',
      'replyingTo': 'Replying to {name}',
      'replyingToQuote': 'Replying to {name}: {text}',
      'cancelReply': 'Cancel reply',
      'attach': 'Attach',
      'send': 'Send',
      'record': 'Record voice message',
      'recordHint': 'Hold to record, release to send',
      'recording': 'Recording, {duration}',
      'deleteRecording': 'Delete recording',
      'slideToCancel': 'Slide to cancel',
      'slideLeftToCancel': 'Slide left to cancel',
      'slideRightToCancel': 'Slide right to cancel',
      'slideUpToLock': 'Slide up to lock recording',
      'preview': 'Preview',
      'simulated': 'Simulated recording',
      'tooShort': 'Too short — hold a little longer',
      'micAsked': 'Allow microphone access, then hold to record',
      'micOff': 'Microphone access is off — turn it on in Settings',
      'play': 'Play voice message',
      'pause': 'Pause voice message',
      'speed': 'Playback speed {speed}',
      'playing': 'Playing, {percent} percent',
      'scrollToLatest': 'Scroll to latest',
      'scrollToLatestNew': 'Scroll to latest, {n} new',
      'closePhoto': 'Close photo',
      'openPhoto': 'Opens the photo full screen',
      'back': 'Back',
      'call': 'Call',
      'video': 'Video call',
      'pinned': 'pinned',
      'muted': 'muted',
      'markRead': 'Read',
      'markUnread': 'Unread',
      'pin': 'Pin',
      'unpin': 'Unpin',
      'mute': 'Mute',
      'unmute': 'Unmute',
      'reactions': 'reactions {list}',
      'replyingToShort': 'replying to {name}',
    },
    'sw': {
      'message': 'Ujumbe',
      'photo': 'Picha',
      'photoCaption': 'Picha: {caption}',
      'voiceMessage': 'Ujumbe wa sauti',
      'voiceMessageLength': 'Ujumbe wa sauti ({duration})',
      'voicePreview': '🎤 Ujumbe wa sauti · {duration}',
      'photoPreview': '📷 {caption}',
      'you': 'Wewe',
      'youPrefix': 'Wewe: {text}',
      'today': 'Leo',
      'yesterday': 'Jana',
      'typing': 'Anaandika',
      'typingInline': 'anaandika',
      'typing1': '{a} anaandika…',
      'typing2': '{a} na {b} wanaandika…',
      'typing3': '{a}, {b} na {c} wanaandika…',
      'typingMany': '{a}, {b} na wengine {n} wanaandika…',
      'online': 'Mtandaoni',
      'nameOnline': '{name}, mtandaoni',
      'unread1': 'Ujumbe 1 haujasomwa',
      'unreadMany': 'Jumbe {n} hazijasomwa',
      'unreadCount': '{n} hazijasomwa',
      'sending': 'Inatuma',
      'sent': 'Imetumwa',
      'delivered': 'Imefika',
      'read': 'Imesomwa',
      'failed': 'Haijafika',
      'retry': 'Haijafika · Gusa ujaribu tena',
      'retryLabel': 'Haijafika. Jaribu tena',
      'reply': 'Jibu',
      'copy': 'Nakili',
      'delete': 'Futa',
      'close': 'Funga',
      'reactWith': 'Jibu kwa {emoji}',
      'reactHeart': 'Jibu kwa moyo',
      'replyingTo': 'Unamjibu {name}',
      'replyingToQuote': 'Unamjibu {name}: {text}',
      'cancelReply': 'Ghairi jibu',
      'attach': 'Ambatisha',
      'send': 'Tuma',
      'record': 'Rekodi ujumbe wa sauti',
      'recordHint': 'Shikilia kurekodi, achilia kutuma',
      'recording': 'Inarekodi, {duration}',
      'deleteRecording': 'Futa rekodi',
      'slideToCancel': 'Telezesha kughairi',
      'slideLeftToCancel': 'Telezesha kushoto kughairi',
      'slideRightToCancel': 'Telezesha kulia kughairi',
      'slideUpToLock': 'Telezesha juu kufunga rekodi',
      'preview': 'Onyesho',
      'simulated': 'Rekodi ya majaribio',
      'tooShort': 'Fupi mno — shikilia kidogo zaidi',
      'micAsked': 'Ruhusu maikrofoni, kisha shikilia kurekodi',
      'micOff': 'Maikrofoni imezimwa — iwashe kwenye Mipangilio',
      'play': 'Cheza ujumbe wa sauti',
      'pause': 'Simamisha ujumbe wa sauti',
      'speed': 'Kasi ya kucheza {speed}',
      'playing': 'Inacheza, asilimia {percent}',
      'scrollToLatest': 'Nenda kwa ujumbe wa mwisho',
      'scrollToLatestNew': 'Nenda kwa ujumbe wa mwisho, {n} mpya',
      'closePhoto': 'Funga picha',
      'openPhoto': 'Hufungua picha skrini nzima',
      'back': 'Rudi',
      'call': 'Piga simu',
      'video': 'Simu ya video',
      'pinned': 'imebandikwa',
      'muted': 'imenyamazishwa',
      'markRead': 'Soma',
      'markUnread': 'Haijasomwa',
      'pin': 'Bandika',
      'unpin': 'Bandua',
      'mute': 'Nyamazisha',
      'unmute': 'Rejesha sauti',
      'reactions': 'hisia {list}',
      'replyingToShort': 'akimjibu {name}',
    },
    'fr': {
      'message': 'Message',
      'photo': 'Photo',
      'photoCaption': 'Photo : {caption}',
      'voiceMessage': 'Message vocal',
      'voiceMessageLength': 'Message vocal ({duration})',
      'voicePreview': '🎤 Message vocal · {duration}',
      'photoPreview': '📷 {caption}',
      'you': 'Vous',
      'youPrefix': 'Vous : {text}',
      'today': 'Aujourd’hui',
      'yesterday': 'Hier',
      'typing': 'En train d’écrire',
      'typingInline': 'écrit',
      'typing1': '{a} écrit…',
      'typing2': '{a} et {b} écrivent…',
      'typing3': '{a}, {b} et {c} écrivent…',
      'typingMany': '{a}, {b} et {n} autres écrivent…',
      'online': 'En ligne',
      'nameOnline': '{name}, en ligne',
      'unread1': '1 message non lu',
      'unreadMany': '{n} messages non lus',
      'unreadCount': '{n} non lus',
      'sending': 'Envoi',
      'sent': 'Envoyé',
      'delivered': 'Distribué',
      'read': 'Lu',
      'failed': 'Non distribué',
      'retry': 'Non distribué · Touchez pour réessayer',
      'retryLabel': 'Non distribué. Réessayer',
      'reply': 'Répondre',
      'copy': 'Copier',
      'delete': 'Supprimer',
      'close': 'Fermer',
      'reactWith': 'Réagir avec {emoji}',
      'reactHeart': 'Réagir avec un cœur',
      'replyingTo': 'Réponse à {name}',
      'replyingToQuote': 'Réponse à {name} : {text}',
      'cancelReply': 'Annuler la réponse',
      'attach': 'Joindre',
      'send': 'Envoyer',
      'record': 'Enregistrer un message vocal',
      'recordHint': 'Maintenez pour enregistrer, relâchez pour envoyer',
      'recording': 'Enregistrement, {duration}',
      'deleteRecording': 'Supprimer l’enregistrement',
      'slideToCancel': 'Glisser pour annuler',
      'slideLeftToCancel': 'Glisser à gauche pour annuler',
      'slideRightToCancel': 'Glisser à droite pour annuler',
      'slideUpToLock': 'Glisser vers le haut pour verrouiller',
      'preview': 'Aperçu',
      'simulated': 'Enregistrement simulé',
      'tooShort': 'Trop court — maintenez un peu plus',
      'micAsked': 'Autorisez le micro, puis maintenez pour enregistrer',
      'micOff': 'Le micro est désactivé — activez-le dans Réglages',
      'play': 'Lire le message vocal',
      'pause': 'Mettre en pause le message vocal',
      'speed': 'Vitesse de lecture {speed}',
      'playing': 'Lecture, {percent} pour cent',
      'scrollToLatest': 'Aller au dernier message',
      'scrollToLatestNew': 'Aller au dernier message, {n} nouveaux',
      'closePhoto': 'Fermer la photo',
      'openPhoto': 'Ouvre la photo en plein écran',
      'back': 'Retour',
      'call': 'Appeler',
      'video': 'Appel vidéo',
      'pinned': 'épinglée',
      'muted': 'en sourdine',
      'markRead': 'Lu',
      'markUnread': 'Non lu',
      'pin': 'Épingler',
      'unpin': 'Désépingler',
      'mute': 'Sourdine',
      'unmute': 'Réactiver',
      'reactions': 'réactions {list}',
      'replyingToShort': 'en réponse à {name}',
    },
  };

  /// The string for [key] in [locale], falling back to English.
  static String lookup(String key, Locale locale,
      [Map<String, Object> args = const {}]) {
    var s = provider?.call(key, locale) ??
        bundled[locale.languageCode]?[key] ??
        bundled['en']![key] ??
        key;
    args.forEach((k, v) => s = s.replaceAll('{$k}', '$v'));
    return s;
  }

  /// The string for [key] in the locale around [context], with `{placeholders}` filled.
  static String of(BuildContext context, String key,
          [Map<String, Object> args = const {}]) =>
      lookup(key, localeOf(context), args);

  /// The locale around [context], or English.
  static Locale localeOf(BuildContext context) =>
      Localizations.maybeLocaleOf(context) ?? const Locale('en');
}
